Models/MyCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManGaStore.Models
{
    public class MyCart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(ManGa manga, int quantity)
    {
        CartLine line = Lines
        .Where(b => b.ManGa.ManGaID == manga.ManGaID)
        .FirstOrDefault();
        if (line == null)
        {
            Lines.Add(new CartLine
            {
                ManGa = manga,
                Quantity = quantity
            });
        }
        else
        {
            line.Quantity += quantity;
        }
    }
        public virtual void RemoveLine(ManGa manga) =>
        Lines.RemoveAll(l => l.ManGa.ManGaID == manga.ManGaID);
         public decimal ComputeTotalValue() =>
        Lines.Sum(e => e.ManGa.Price * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }

    public class CartLine
    {
        public int CartLineID { get; set; }
        public ManGa ManGa { get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using ManGaStore.Models;
using System.Linq;
namespace ManGaStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private MyCart cart;
        public OrderController(IOrderRepository repoService, MyCart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Completed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ManGaStore.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/MyCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ManGaStore.MyTagHelper;
using ManGaStore.Models;
using System.Linq;
namespace ManGaStore.Pages
{
    public class MyCartModel : PageModel
    {
        private IManGaStoreRepository repository;
        public MyCartModel(IManGaStoreRepository repo, MyCart myCartService)
        {
            repository = repo;
            myCart = myCartService;
        }
        public MyCart myCart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long mangaId, string returnUrl)
        {
            ManGa manga = repository.ManGas
            .FirstOrDefault(b => b.ManGaID == mangaId);
            myCart.AddItem(manga, 1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long mangaId, string returnUrl)
        {
            myCart.RemoveLine(myCart.Lines.First(cl =>
            cl.ManGa.ManGaID == mangaId).ManGa);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Pages/Completed.cshtml
@page
<div class="text-center">
    <h3>Thanks for placing order #@OrderId</h3>
    <p>We'll ship your goods as soon as possible.</p>
    <a class="btn btn-info" asp-controller="Home">Return to Store</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Pages/MyCart.cshtml
@page
@model MyCartModel
<h2>Your cart</h2>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.myCart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.ManGa.Title</td>
                <td class="text-right">@line.ManGa.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity * line.ManGa.Price).ToString("c"))
                </td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="ManGaID"
                               value="@line.ManGa.ManGaID" />
                        <input type="hidden" name="returnUrl"
                               value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.myCart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-info" href="@Model.ReturnUrl">Continue shopping</a>
    <a class="btn btn-info" asp-action="Checkout" asp-controller="Order">
        Checkout Now
    </a>
</div>

Pages/_MyCartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Manga Store</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">MANGA STORE</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>